[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "twd-desktop"
version = "1.0.0"
description = "Management CLI for Termux Linux Desktops"
scripts = {twd-desktop = "twd_desktop.main:main"}
